[package]
name = "tf-log-parser"
version = "0.1.0"
edition = "2018"

[dependencies]
steamid-ng = "1"
nom = "6"
enum-iterator = "0.7"
chrono = "0.4"
thiserror = "1"

[dev-dependencies]
main_error = "0.1"