[package]
name = "tf-log-parser"
version = "0.1.0"
edition = "2018"

[dependencies]
steamid-ng = "1"
nom = "6"
enum-iterator = "0.7"
chrono = { version = "0.4", features = ["serde"] }
thiserror = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
main_error = "0.1"
paste = "1"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "bench"
harness = false