[package]
name = "tf-log-parser-derive"
version = "0.1.0"
edition = "2021"

[lib]
name = "tf_log_parser_derive"
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
proc-macro2 = "1.0"
syn_util = "0.4"

[dev-dependencies]
tf-log-parser = { version = "0.1", path = ".." }